.pragma library

// Pushes all current UI values to Score ports after play() resets port state 

function pushValuesToScore(Score, processes, values) {
    var p = processes
    try {
        if (p.prompt_composer.keywords)
            Score.setValue(p.prompt_composer.keywords, values.prompt)
        if (p.streamDiffusion.workflow)
            Score.setValue(p.streamDiffusion.workflow, values.workflow)
        if (p.streamDiffusion.engines)
            Score.setValue(p.streamDiffusion.engines, values.enginePath)
        if (p.streamDiffusion.seed)
            Score.setValue(p.streamDiffusion.seed, values.seed)
        if (p.streamDiffusion.timesteps)
            Score.setValue(p.streamDiffusion.timesteps, values.timesteps)
        if (p.streamDiffusion.guidance)
            Score.setValue(p.streamDiffusion.guidance, values.guidance)
        if (p.streamDiffusion.guidance_type)
            Score.setValue(p.streamDiffusion.guidance_type, values.guidanceType)
        if (p.streamDiffusion.delta)
            Score.setValue(p.streamDiffusion.delta, values.delta)
        if (p.streamDiffusion.denoising_batch)
            Score.setValue(p.streamDiffusion.denoising_batch, values.denoisingBatch)
        if (p.streamDiffusion.add_noise)
            Score.setValue(p.streamDiffusion.add_noise, values.addNoise)
        if (p.streamDiffusion.manual_mode)
            Score.setValue(p.streamDiffusion.manual_mode, values.manualMode)
        if (p.streamDiffusion.resolution)
            Score.setValue(p.streamDiffusion.resolution, values.resolution)
        if (p.shape.maskShapeMode)
            Score.setValue(p.shape.maskShapeMode, values.shapeType)
        if (p.shape.color) {
            var c = Qt.hsla(values.hue, 0.7, values.brightness, 1.0)
            Score.setValue(p.shape.color, [c.r, c.g, c.b, 1.0])
        }
        if (p.shape.shapeWidth)
            Score.setValue(p.shape.shapeWidth, values.shapeWidth)
        if (p.shape.shapeHeight)
            Score.setValue(p.shape.shapeHeight, values.shapeHeight)
        if (p.shape.horizontalRepeat)
            Score.setValue(p.shape.horizontalRepeat, values.shapeHRepeat)
        if (p.shape.verticalRepeat)
            Score.setValue(p.shape.verticalRepeat, values.shapeVRepeat)
        if (p.shape.center)
            Score.setValue(p.shape.center, [values.shapeX / 512.0, values.shapeY / 512.0])
        if (p.shape.invertMask)
            Score.setValue(p.shape.invertMask, values.invert)
        if (p.video_Mixer.alpha1)
            Score.setValue(p.video_Mixer.alpha1, values.shapeAmount)
        if (p.video_Mixer.alpha2)
            Score.setValue(p.video_Mixer.alpha2, values.smokeAmount)
        if (p.video_Mixer.alpha3)
            Score.setValue(p.video_Mixer.alpha3, values.voronoiAmount)
        if (p.video_Mixer.alpha4)
            Score.setValue(p.video_Mixer.alpha4, values.noiseAmount)
        if (p.video_Mixer.alpha5)
            Score.setValue(p.video_Mixer.alpha5, values.perlinAmount)
        if (p.video_Mixer.alpha7)
            Score.setValue(p.video_Mixer.alpha7, values.imageAmount)
        if (p.video_Mixer.alpha8)
            Score.setValue(p.video_Mixer.alpha8, values.cameraAmount)
        if (p.voronoi.seed)        Score.setValue(p.voronoi.seed,        values.voronoiSeed)
        if (p.voronoi.iregularity) Score.setValue(p.voronoi.iregularity, values.voronoiIregularity)
        if (p.voronoi.blur)        Score.setValue(p.voronoi.blur,        values.voronoiBlur)
        if (p.voronoi.scale)       Score.setValue(p.voronoi.scale,       values.voronoiScale)
        if (p.white_Noise.seed)    Score.setValue(p.white_Noise.seed,    values.whiteNoiseSeed)
        if (p.perlin_Noise.seed)   Score.setValue(p.perlin_Noise.seed,   values.perlinSeed)
        if (p.perlin_Noise.scale)  Score.setValue(p.perlin_Noise.scale,  values.perlinScale)
    } catch(e) {
        console.warn("[ScoreBridge] pushValuesToScore error:", e)
    }
}
