name: Build Koaia

on:
  push: 
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    name: Package Custom App - ${{ matrix.platform }}
    runs-on: ${{ matrix.os }}
    container: ${{ matrix.container }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - os: [self-hosted, linux, x64, sat-builder]
            container: "ubuntu:noble"
            platform: linux-x86_64
            artifact-name: linux-x86_64
          - os: macos-latest
            container: ""
            platform: macos-arm
            artifact-name: macos-arm
          - os: windows-latest
            container: ""
            platform: windows
            artifact-name: windows

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7

      - name: Package custom ossia score app
        uses: ossia/actions/package-custom-app@master
        with:
          app-name: "Koaia"
          qml-files: "qml"
          # Optional: Add your score file here
          score-file: "score/app.score"
          release-tag: "continuous"
          platforms: "${{ matrix.platform }}"
          # App metadata
          app-organization: "SAT"
          app-domain: "sat.qc.ca"
          app-identifier: "ca.qc.sat.koaia"
          app-description: "A tool for exploring generative ai"
          app-environment: environment
          app-copyright: "Société des Arts Technologiques"
          app-version: "1.0"
          app-png: "qml/koaia/resources/images/koaia_logo.png" 
          app-icns: "qml/koaia/resources/images/koaia_logo.icns"
          app-ico: "qml/koaia/resources/images/koaia_logo.ico"
          # Optional: macOS code signing (requires secrets to be set in repository)
          macos-certificate-base64: ${{ secrets.MAC_CERT_B64 }}
          macos-certificate-password: ${{ secrets.MAC_CERT_PASSWORD }}
          macos-notarize-team-id: ${{ secrets.MAC_NOTARIZE_TEAM_ID }}
          macos-notarize-apple-id: ${{ secrets.MAC_NOTARIZE_APPLE_ID }}
          macos-notarize-password: ${{ secrets.MAC_NOTARIZE_PASSWORD }}

      - name: Upload packages
        uses: actions/upload-artifact@v7
        with:
          name: koaia-${{ matrix.artifact-name }}
          path: packages/
          retention-days: 30
